### ISSUE TITLE
Http auto instrumentation fails when using @FileInterceptor

### ISSUE THREAD

**Issue by benitezho** [pragmaticivan/nestjs-otel#42] opened 2021-07-01 21:26 UTC
Sample fork : https://github.com/benitezho/nestjs-otel

Using: nodeJS 16.1.0

### Description 
I uploaded a sample nestjs main module ready to run.
In the example i created a *AppController* that outputs on the console the active span from the current context, the line that reproduces the issue its: 
`// @UseInterceptors(FileInterceptor('field'))`
If you uncomment this line, the active span from the current context its undefined when a new request its incoming. 

My guess is that Nestjs's @FileInterceptor that uses multer under the hood, somehow it's replacing the async hook request listeners. For that reason, i don't know if this issue should be here.

**Comment by pragmaticivan** [comment] 2021-07-01 22:33
Hi @benitezho I was able to run that repo locally and replicate the problem. It appears it's actually related to open telemetry http instrumentation. I would suggest opening a ticket on https://github.com/open-telemetry/opentelemetry-js.

It appears other folks had the same problem previously: https://gitter.im/open-telemetry/opentelemetry-node?at=5f2136f33eef7e1ffe3f423c
<img width="1239" alt="Screen_Shot_2021-07-01_at_5 25 19_PM" src="https://user-images.githubusercontent.com/301291/124196615-6638a200-da92-11eb-9014-14411f04a146.png">

**Comment by pragmaticivan** [comment] 2021-07-01 22:34
The parts you are using are not dependent on anything from that lib after all.

**Comment by pragmaticivan** [comment] 2021-07-01 22:34
If you can try to replicate the example outside next with just an express server and multer

**Comment by pragmaticivan** [comment] 2021-07-02 00:35
Will leave it open for a bit. I was able to configure a raw example of express and multer. https://github.com/pragmaticivan/express-multer-otel-bug and was not able to reproduce the error.

I also found that having multiple routes, where one has multer, disables http instrumentation alltogether.

**Comment by pragmaticivan** [comment] 2021-07-02 00:41
I was also able to verify it's fully related to `FileInterceptor`.

**Comment by benitezho** [comment] 2021-07-02 15:58
@pragmaticivan Using Multer through Nestjs's module configuration fixes the problem with the otel active context, avoiding the use of @FileInterceptor decorator.
See https://github.com/benitezho/nestjs-otel/commit/68017239b3d2a74b709a70ee5e792cc60f87f0ba

With that said, i guess the problem its with how @FileInteceptor uses multer under the hood, i didn't look through the @FileInterceptor source code yet though.

**Comment by pratimsc** [comment] 2021-07-24 12:29
@pragmaticivan - any advice on how to use this, when `FileInterceptor` is used?
The instrumentation works great, with all apps, except where `FileInterceptor` is used.

**Comment by pragmaticivan** [comment] 2021-07-24 21:13
Hi @pratimsc I'm still looking into FileInterceptor problem. It appears the dependencies for that get load after instrumentation.

A workaround is to use Multer as a middleware (which is the same thing FileInterceptor does) ex: https://github.com/benitezho/nestjs-otel/commit/68017239b3d2a74b709a70ee5e792cc60f87f0ba

**Comment by pragmaticivan** [comment] 2021-07-28 00:52
@pratimsc @benitezho a lot of the problems I found when I created that lib are going to be fixed in this PR: https://github.com/pragmaticivan/nestjs-otel/pull/55

It will require a Major version though. FYI.

**Comment by pragmaticivan** [comment] 2021-07-28 01:00
This should be fixed here: https://github.com/pragmaticivan/nestjs-otel/releases/tag/v2.0.0

**Closed by pragmaticivan** 2021-07-28 01:00 UTC
